from classes import Species
from creatureTypes import *

speciesList = [
    Species(
        name = "low powered",
        type1 = beastType,
        type2 = None,
        baseHP = 48,
        baseEnergy = 48,
        baseStrength = 48,
        baseMagic = 48,
        baseSkill = 48,
        baseSpeed = 48,
        baseDefense = 48,
        baseResistance = 48,
    ),

    Species(
        name = "medium low",
        type1 = beastType,
        type2 = None,
        baseHP = 50,
        baseEnergy = 50,
        baseStrength = 50,
        baseMagic = 50,
        baseSkill = 50,
        baseSpeed = 50,
        baseDefense = 50,
        baseResistance = 50,
    ),

    Species(
        name = "medium",
        type1 = beastType,
        type2 = None,
        baseHP = 53,
        baseEnergy = 53,
        baseStrength = 53,
        baseMagic = 53,
        baseSkill = 53,
        baseSpeed = 53,
        baseDefense = 53,
        baseResistance = 53,
    ),

    Species(
        name = "medium high",
        type1 = beastType,
        type2 = None,
        baseHP = 55,
        baseEnergy = 55,
        baseStrength = 55,
        baseMagic = 55,
        baseSkill = 55,
        baseSpeed = 55,
        baseDefense = 55,
        baseResistance = 55,
    ),

    Species(
        name = "high",
        type1 = beastType,
        type2 = None,
        baseHP = 56,
        baseEnergy = 56,
        baseStrength = 56,
        baseMagic = 56,
        baseSkill = 56,
        baseSpeed = 56,
        baseDefense = 56,
        baseResistance = 56,
    ),

    Species(
        name = "legend",
        type1 = beastType,
        type2 = None,
        baseHP = 58,
        baseEnergy = 58,
        baseStrength = 58,
        baseMagic = 58,
        baseSkill = 58,
        baseSpeed = 58,
        baseDefense = 58,
        baseResistance = 58,
    ),

    Species(
        name = "max",
        type1 = beastType,
        type2 = None,
        baseHP = 100,
        baseEnergy = 100,
        baseStrength = 100,
        baseMagic = 100,
        baseSkill = 100,
        baseSpeed = 100,
        baseDefense = 100,
        baseResistance = 100,
    ),

    Species(
        name = "Bloodfang",
        type1 = necroticType,
        type2 = beastType,
        baseHP = 62,
        baseEnergy = 42,
        baseStrength = 76,
        baseMagic = 50,
        baseSkill = 70,
        baseSpeed = 65,
        baseDefense = 40,
        baseResistance = 35,
    ),

    Species(
        name = "Lureghast",
        type1 = necroticType,
        type2 = fireType,
        baseHP = 40,
        baseEnergy = 65,
        baseStrength = 25,
        baseMagic = 75,
        baseSkill = 65,
        baseSpeed = 55,
        baseDefense = 35,
        baseResistance = 60,
    ),

    Species(
        name = "coreforge",
        type1 = fireType,
        type2 = earthType,
        baseHP = 65,
        baseEnergy = 60,
        baseStrength = 75,
        baseMagic = 75,
        baseSkill = 35,
        baseSpeed = 25,
        baseDefense = 65,
        baseResistance = 50,
    ),

    Species(
        name = "tardigarde",
        type1 = waterType,
        type2 = arcaneType,
        baseHP = 88,
        baseEnergy = 44,
        baseStrength = 22,
        baseMagic = 35,
        baseSkill = 26,
        baseSpeed = 12,
        baseDefense = 95,
        baseResistance = 98,
    ),

    Species(
        name = "swiftwing",
        type1 = airType,
        type2 = None,
        baseHP = 30,
        baseEnergy = 60,
        baseStrength = 20,
        baseMagic = 55,
        baseSkill = 55,
        baseSpeed = 85,
        baseDefense = 30,
        baseResistance = 45,
    ),
]